title: GaiaViz Docs
description: Everything you need to get started using GaiaViz!
theme: just-the-docs

url: https://gaiaviz.github.io/docs

aux_links:
  Docs Repository: https://github.com/gaiaviz/docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark


callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  info:
    title: Info
    color: blue
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  highlight:
    title: Highlight
    color: purple
