title: GaiaViz Docs
description: Everything you need to get started using GaiaViz!
theme: just-the-docs

url: https://gaiaviz.github.io/docs



# Aux links for the upper right navigation
aux_links:
  Download GaiaViz:  https://gaiaviz.com/downloads
  Docs Repository: https://github.com/gaiaviz/docs
  Technical Docs: https://github.com/gaiaviz/gaiaviz/wiki


# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


# Color scheme supports "light" (default) and "dark"
color_scheme: dark


callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  info:
    title: Info
    color: blue
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  highlight:
    title: Highlight
    color: purple
